### PR TITLE
Feature/improvements - Improve social shares

### PR DESCRIPTION
**Pull request by danielGalvao**
Improve social shares configs

### CODE REVIEW

**Comment by danielGalvao** [comment]
@jvcjunior What's wrong?  All checks have failed - ci/stage-ci — Error

**Comment by danvitoriano** [comment]
@jvcjunior, @rodrigooler disse q o stage parou! @galvaodev

**Comment by jvcjunior** [comment]
Eita.. estranho. Vou conferir o que está acontecendo!

**Comment by danvitoriano** [comment]
👏

**Pull request merged**
