### PR TITLE
POST-0.3.5-RC 👉 New Layout v1.0.0 [Master]

### PR DESCRIPTION
**Pull request by danvitoriano**
### What does this PR do?

The first oficial release made for the conf day.

Improve part of new layout proposal at #53, without the monkey, respecting the branding design original made by SENAI. This merge came from [this branch feature/layout](https://github.com/react-brasil/conf/tree/feature/layout)

### Main changes:

- Remove components: C4P, Help, Topics
- Add components: Supporters
- Rename components: Pitch > Event, BuyTickets > BuyIngressos
- Add new speakers and avatars
- Add webm video to hero section
- Add an image to event pitch
- Fix link colors from Contact Section
- Adjust layout to full responsive mode
- Change svg logo color due to WCAG contrast background
- Change colors after WCAG colors contrast analyser to acessibility
- Adjust font size to improve readability
- Change Augusta Theater photo
- Add new photos from theater for further slideshow gallery

The site is written in Portuguese, but browsers with langauage detection can translate it. For english version the translation is ok for me. Someone can use it to solve #35 

Sorry for long PR.

<3

### CODE REVIEW

**Comment by danielGalvao** [comment]
I tried to run your branch and returned this error for me
error

**Comment by danielGalvao** [comment]
yarn start

**Comment by danvitoriano** [comment]
you need to run `npm install` again @danielGalvao due to new packages installed ;)

**Comment by danielGalvao** [comment]
Nice!!! 
It's snowing...

**Pull request merged**
